apply plugin: 'com.android.application'

def gitLastCommitHash = providers.exec {
    commandLine('git', 'rev-parse', '--short', 'HEAD')
}.standardOutput.asText.get().toString().trim()

android {
    compileSdk 35

    buildFeatures {
        dataBinding true
        buildConfig true
    }

    defaultConfig {
        applicationId "com.vpe_soft.intime.intime.dev"
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 21
        versionName "1.1.8"
        buildConfigField "String", "GIT_LAST_COMMIT_HASH", "\"${gitLastCommitHash}\""

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.vpe_soft.intime.intime'

    sourceSets {
        // Проверьте, что указано 'androidTest', а не просто 'test' или 'main'
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
    }
}

dependencies {
    implementation 'androidx.work:work-runtime:2.11.2'

    def room_version = "2.8.4"  // Актуальная версия на февраль 2025
    implementation("androidx.room:room-runtime:$room_version")
    annotationProcessor("androidx.room:room-compiler:$room_version")  // Для Java

    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.legacy:legacy-support-v13:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20251224'
    testImplementation 'org.robolectric:robolectric:4.16.1'
    testImplementation 'androidx.test:core:1.7.0'

    androidTestImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation("androidx.room:room-testing:$room_version")
}
