apply plugin: 'com.android.application'

def gitLastCommitHash = providers.exec {
    commandLine('git', 'rev-parse', '--short', 'HEAD')
}.standardOutput.asText.get().toString().trim()

android {
    compileSdk 35

    buildFeatures {
        dataBinding true
        buildConfig true
    }

    defaultConfig {
        applicationId "com.vpe_soft.intime.intime"
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 21
        versionName "1.1.8"
        buildConfigField "String", "GIT_LAST_COMMIT_HASH", "\"${gitLastCommitHash}\""

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.vpe_soft.intime.intime'
}

dependencies {
    //implementation 'androidx.activity:activity:1.10.0'
    def room_version = "2.6.1"  // Актуальная версия на февраль 2025
    implementation("androidx.room:room-runtime:$room_version")
    annotationProcessor("androidx.room:room-compiler:$room_version")  // Для Java

    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.legacy:legacy-support-v13:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
}
